version: "1"
rules:
  - base: alpha
    upstream: EL-Coders:alpha
    mergeMethod: rebase
    mergeUnstable: false
  - base: beta
    upstream: EL-Coders:beta
    mergeMethod: rebase
  - base: master
    upstream: EL-Coders:master
    mergeMethod: rebase
